### ISSUE TITLE
Missing 0.1.7 git tag and support for protobuf 3.0.0-beta-1

### ISSUE THREAD

**Issue by xmikos** [tgalal/python-axolotl#3]
Please can you add git tag for version 0.1.7? It's missing from GitHub repo and that makes distributing python-axolotl cumbersome.

Also can you please remove limitation on protobuf <3.0.0-alpha-2 from setup.py? I have tested it with protobuf 3.0.0-alpha-3 and 3.0.0-beta-1 and it works without problems.

**Comment by benediktg** [comment]
I would even say the dependency on protobuf should be >= 2.6.1 because otherwise it is not possible to enable the OMEMO plugin in Gajim.

**Comment by lovetox** [comment]
@benediktg the reason is not python-axolotl

i think the reason is how google distributes the python package

https://github.com/google/protobuf/issues/1296

python axolotl works even with the newest protobuf version in my experience, though this depends on how you installed it

but it always works with 2.6.1
